### ISSUE TITLE
Login config ??

### ISSUE THREAD

**Issue by premnathdey** [TheArhaam/Android-StudentAMS#1]
Hello, 
I want to know how did you configure you SiginUP. 
As building the dependency I am still not able to signup as a staff.

**Comment by TheArhaam** [comment]
Could you please elaborate the issue you are facing?
Have you created a Firebase project and configured everything properly?

**Comment by premnathdey** [comment]
The issue was solved I have not properly configured my firebase.

Thanks 🔥

**Comment by TheArhaam** [comment]
Alright, let me know if you're facing any other issues
